language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r test_project/requirements.txt --use-mirrors
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls

